name: golangci-lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libpcap-dev

      - name: golangci-lint (agent)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: agent

      - name: golangci-lint (shared)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: shared

      - name: golangci-lint (tap)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: tap

      - name: golangci-lint (cli)
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: cli
